"""add description and rating column for company table

Revision ID: caced3636200
Revises: 3d7fe8ae15dc
Create Date: 2025-09-22 16:25:55.311333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caced3636200'
down_revision: Union[str, Sequence[str], None] = '3d7fe8ae15dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'companies',
        sa.Column('description', sa.String(), nullable=True),
    )
    op.add_column(
        'companies',
        sa.Column('rating', sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'rating')
    op.drop_column('companies', 'description')
    # ### end Alembic commands ###
